STATE_CODE_DROP = 'state-code-dd'
STATE_CODE_INPUT = 'state-code-input'

METRO_DROP = 'metro-dd'
METRO_INPUT = 'metro-input'
REGION_DROP = 'region-dd'
PROPERTY_TYPE_DROP = 'proptype-dd'
METRIC_DROP = 'metric-dd'
US_MAP = 'us-map'
HOUSING_TABLE_ID = 'house-table'
COL_MSP_YOY = 'msp-yoy'
COL_MLP_YOY = 'mlp-yoy'
COL_HS_YOY = 'hs-yoy'
COL_INV_YOY = 'inv-yoy'
COL_ASTL_YOY = 'astl-yoy'

SELECT_COMP = 'compare-to-selector'

BTN_PREV = 'prev-button'
BTN_NXT = 'next-button'

DIV_PGNUM = 'page-number'
TABS = 'tabs'
TABS_CONTENT = 'tabs-content'
TAB_1 = 'tab1'
TAB_2 = 'tab2'
TAB_DIVS = 'tab-divs'