metric_list = [
    'median_sale_price',
    'median_sale_price_yoy',
    'median_list_price',
    'median_list_price_yoy',
    'homes_sold',
    'homes_sold_yoy',
    'pending_sales',
    'new_listings',
    'inventory',
    'inventory_yoy',
    'median_dom',
    'median_dom_yoy',
    'avg_sale_to_list',
    'avg_sale_to_list_yoy'
]

percentage_metric_list = [
    'median_sale_price_yoy',
    'median_list_price_yoy',
    'homes_sold_yoy',
    'inventory_yoy',
    'avg_sale_to_list_yoy'
]

# Define the list of table columns including region, property_type, period_end and the metrics
table_columns = [
    'region',
    'region_type',
    'property_type',
    'period_end',
    'median_sale_price_yoy',
    'median_list_price_yoy',
    'homes_sold_yoy',
    'inventory_yoy',
    'avg_sale_to_list_yoy'
]


column_definitions = {
    'period_begin': 'TEXT',
    'period_end': 'TEXT',
    'period_duration': 'INTEGER',
    'region_type': 'TEXT',
    'region_type_id': 'INTEGER',
    'table_id': 'INTEGER',
    'is_seasonally_adjusted': 'TEXT',
    'region': 'TEXT',
    'city': 'TEXT',
    'state': 'TEXT',
    'state_code': 'TEXT',
    'property_type': 'TEXT',
    'property_type_id': 'INTEGER',
    'median_sale_price': 'REAL',
    'median_sale_price_mom': 'REAL',
    'median_sale_price_yoy': 'REAL',
    'median_list_price': 'REAL',
    'median_list_price_mom': 'REAL',
    'median_list_price_yoy': 'REAL',
    'median_ppsf': 'REAL',
    'median_ppsf_mom': 'REAL',
    'median_ppsf_yoy': 'REAL',
    'median_list_ppsf': 'REAL',
    'median_list_ppsf_mom': 'REAL',
    'median_list_ppsf_yoy': 'REAL',
    'homes_sold': 'REAL',
    'homes_sold_mom': 'REAL',
    'homes_sold_yoy': 'REAL',
    'pending_sales': 'REAL',
    'pending_sales_mom': 'REAL',
    'pending_sales_yoy': 'REAL',
    'new_listings': 'REAL',
    'new_listings_mom': 'REAL',
    'new_listings_yoy': 'REAL',
    'inventory': 'REAL',
    'inventory_mom': 'REAL',
    'inventory_yoy': 'REAL',
    'months_of_supply': 'REAL',
    'months_of_supply_mom': 'REAL',
    'months_of_supply_yoy': 'REAL',
    'median_dom': 'REAL',
    'median_dom_mom': 'REAL',
    'median_dom_yoy': 'REAL',
    'avg_sale_to_list': 'REAL',
    'avg_sale_to_list_mom': 'REAL',
    'avg_sale_to_list_yoy': 'REAL',
    'sold_above_list': 'REAL',
    'sold_above_list_mom': 'REAL',
    'sold_above_list_yoy': 'REAL',
    'price_drops': 'REAL',
    'price_drops_mom': 'REAL',
    'price_drops_yoy': 'REAL',
    'off_market_in_two_weeks': 'REAL',
    'off_market_in_two_weeks_mom': 'REAL',
    'off_market_in_two_weeks_yoy': 'REAL',
    'parent_metro_region': 'TEXT',
    'parent_metro_region_metro_code': 'INTEGER',
    'last_updated': 'TEXT'
}

column_definitions_pg = {'period_begin': 'String', 'period_end': 'String', 'period_duration': 'Integer', 'region_type': 'String', 'region_type_id': 'Integer', 'table_id': 'Integer', 'is_seasonally_adjusted': 'String', 'region': 'String', 'city': 'String', 'state': 'String', 'state_code': 'String', 'property_type': 'String', 'property_type_id': 'Integer', 'median_sale_price': 'Float', 'median_sale_price_mom': 'Float', 'median_sale_price_yoy': 'Float', 'median_list_price': 'Float', 'median_list_price_mom': 'Float', 'median_list_price_yoy': 'Float', 'median_ppsf': 'Float', 'median_ppsf_mom': 'Float', 'median_ppsf_yoy': 'Float', 'median_list_ppsf': 'Float', 'median_list_ppsf_mom': 'Float', 'median_list_ppsf_yoy': 'Float', 'homes_sold': 'Float', 'homes_sold_mom': 'Float', 'homes_sold_yoy': 'Float', 'pending_sales': 'Float', 'pending_sales_mom': 'Float', 'pending_sales_yoy': 'Float', 'new_listings': 'Float', 'new_listings_mom': 'Float', 'new_listings_yoy': 'Float', 'inventory': 'Float', 'inventory_mom': 'Float', 'inventory_yoy': 'Float', 'months_of_supply': 'Float', 'months_of_supply_mom': 'Float', 'months_of_supply_yoy': 'Float', 'median_dom': 'Float', 'median_dom_mom': 'Float', 'median_dom_yoy': 'Float', 'avg_sale_to_list': 'Float', 'avg_sale_to_list_mom': 'Float', 'avg_sale_to_list_yoy': 'Float', 'sold_above_list': 'Float', 'sold_above_list_mom': 'Float', 'sold_above_list_yoy': 'Float', 'price_drops': 'Float', 'price_drops_mom': 'Float', 'price_drops_yoy': 'Float', 'off_market_in_two_weeks': 'Float', 'off_market_in_two_weeks_mom': 'Float', 'off_market_in_two_weeks_yoy': 'Float', 'parent_metro_region': 'String', 'parent_metro_region_metro_code': 'Integer', 'last_updated': 'String'}

cohort_raw = [
    {"region": "Chicago, IL metro area", "state_code": "IL", "US_Area": "Midwest"},
    {"region": "Boston, MA metro area", "state_code": "MA", "US_Area": "Northeast"},
    {"region": "Charlotte, NC metro area", "state_code": "NC", "US_Area": "Southeast"},
    {"region": "Houston, TX metro area", "state_code": "TX", "US_Area": "Southwest"},
    {"region": "Los Angeles, CA metro area", "state_code": "CA", "US_Area": "West"},
    {"region": "Des Moines, IA metro area", "state_code": "IA", "US_Area": "Midwest"},
    {"region": "Newark, NJ metro area", "state_code": "NJ", "US_Area": "Northeast"},
    {"region": "Miami, FL metro area", "state_code": "FL", "US_Area": "Southeast"},
    {"region": "Austin, TX metro area", "state_code": "TX", "US_Area": "Southwest"},
    {"region": "Denver, CO metro area", "state_code": "CO", "US_Area": "West"},
    {"region": "Appleton, WI metro area", "state_code": "WI", "US_Area": "Midwest"},
    {"region": "Burlington, VT metro area", "state_code": "VT", "US_Area": "Northeast"},
    {"region": "Bowling Green, KY metro area", "state_code": "KY", "US_Area": "Southeast"},
    {"region": "Tucson, AZ metro area", "state_code": "AZ", "US_Area": "Southwest"},
    {"region": "Billings, MT metro area", "state_code": "MT", "US_Area": "West"},
    {"region": "Detroit, MI metro area", "state_code": "MI", "US_Area": "Midwest"},
    {"region": "Manchester, NH metro area", "state_code": "NH", "US_Area": "Northeast"},
    {"region": "Birmingham, AL metro area", "state_code": "AL", "US_Area": "Southeast"},
    {"region": "Phoenix, AZ metro area", "state_code": "AZ", "US_Area": "Southwest"},
    {"region": "San Jose, CA metro area", "state_code": "CA", "US_Area": "West"},
    {"region": "Springfield, MO metro area", "state_code": "MO", "US_Area": "Midwest"},
    {"region": "Hartford, CT metro area", "state_code": "CT", "US_Area": "Northeast"},
    {"region": "Anniston, AL metro area", "state_code": "AL", "US_Area": "Southeast"},
    {"region": "Dallas, TX metro area", "state_code": "TX", "US_Area": "Southwest"},
    {"region": "Stockton, CA metro area", "state_code": "CA", "US_Area": "West"},
    {"region": "Kansas City, MO metro area", "state_code": "MO", "US_Area": "Midwest"},
    {"region": "Buffalo, NY metro area", "state_code": "NY", "US_Area": "Northeast"},
    {"region": "Fayetteville, AR metro area", "state_code": "AR", "US_Area": "Southeast"},
    {"region": "Santa Fe, NM metro area", "state_code": "NM", "US_Area": "Southwest"},
    {"region": "Jackson, WY metro area", "state_code": "WY", "US_Area": "West"},
    {"region": "Bismarck, ND metro area", "state_code": "ND", "US_Area": "Midwest"},
    {"region": "Pittsburgh, PA metro area", "state_code": "PA", "US_Area": "Northeast"},
    {"region": "Jacksonville, FL metro area", "state_code": "FL", "US_Area": "Southeast"},
    {"region": "Taos, NM metro area", "state_code": "NM", "US_Area": "Southwest"},
    {"region": "Seattle, WA metro area", "state_code": "WA", "US_Area": "West"},
    {"region": "Lincoln, NE metro area", "state_code": "NE", "US_Area": "Midwest"},
    {"region": "Providence, RI metro area", "state_code": "RI", "US_Area": "Northeast"},
    {"region": "Atlanta, GA metro area", "state_code": "GA", "US_Area": "Southeast"},
    {"region": "San Antonio, TX metro area", "state_code": "TX", "US_Area": "Southwest"},
    {"region": "Salt Lake City, UT metro area", "state_code": "UT", "US_Area": "West"},
    {"region": "Cleveland, OH metro area", "state_code": "OH", "US_Area": "Midwest"},
    {"region": "Allentown, PA metro area", "state_code": "PA", "US_Area": "Northeast"},
    {"region": "New Orleans, LA metro area", "state_code": "LA", "US_Area": "Southeast"},
    {"region": "Flagstaff, AZ metro area", "state_code": "AZ", "US_Area": "Southwest"},
    {"region": "Eugene, OR metro area", "state_code": "OR", "US_Area": "West"},
    {"region": "Sioux Falls, SD metro area", "state_code": "SD", "US_Area": "Midwest"},
    {"region": "Portland, ME metro area", "state_code": "ME", "US_Area": "Northeast"},
    {"region": "Jackson, MS metro area", "state_code": "MS", "US_Area": "Southeast"},
    {"region": "Midland, TX metro area", "state_code": "TX", "US_Area": "Southwest"},
    {"region": "Las Vegas, NV metro area", "state_code": "NV", "US_Area": "West"}
]


